"""Freeze training-only feedback repair; no heldout-dependent parameters."""
import argparse,json,sys,time
from pathlib import Path
import numpy as np
from run_exp3_remote_pilot_jobs_v0_125 import emit,sha,ROBOT


def main():
    p=argparse.ArgumentParser();p.add_argument('--base',type=Path,required=True);p.add_argument('--diagnostic',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();base=a.base.resolve();previous=json.loads((base/'execution-001/independent_delivery_001/independent_verification.json').read_text())
    if previous.get('report_valid') is not True:raise ValueError('parent_not_independently_verified')
    diagnosis=json.loads((a.diagnostic/'summary.json').read_text())
    if diagnosis.get('heldout_used') is not False or diagnosis['episodes']!=1000:raise ValueError('diagnosis_not_training_only')
    root=a.output.resolve();root.mkdir(parents=True,exist_ok=False);tc=json.loads((base/'training_configuration.json').read_text());life=json.loads((base/'lifecycle_configuration.json').read_text());repo=Path(life['repo'])
    frame_index=Path(tc['dataset_manifest']).parent/'frame_index.jsonl';q=np.asarray([json.loads(l)['proprio'] for l in frame_index.open()],np.float64);mean=q.mean(0);std=np.maximum(q.std(0),[.1]*7+[.01,.01]);source_cache=base/'execution-001/features/manifest.json'
    tc.update(method_id='exp3_complete_robot_task_oft_feedback_denoising_v0_167',action_adapter_id='openvla_oft_franka_feedback_denoising_v0_167',parent_method_id=tc['method_id'],model_name='OpenVLA-OFT frozen vision-language backbone + learned feedback-aware recurrent robot head',max_steps=32000,save_every=8000,final_checkpoint_rule='step_032000 only; no checkpoint selection on heldout',feature_cache_manifest=str(source_cache),feature_cache_manifest_sha256=sha(source_cache),feature_cache_source_configuration_sha256=sha(base/'training_configuration.json'),proprio_mean=mean.tolist(),proprio_std=std.tolist(),proprio_statistics_source_sha256=sha(frame_index),proprio_augmentation_probability=.75,proprio_noise_std_rad=.005,proprio_noise_correlation=.8,augmentation_seed=167031,motion_loss_gain=4.,motion_loss_scale_rad=.01,training_backbone_frozen=True,learning_rate=.0003)
    tc['proprio_normalization']='training-only per-joint mean/std; std floor .1 rad arm and .01 m fingers; identical saved buffers for both variants'
    tc['augmentation_contract']='Arm proprio only: seeded independent correlated .005 rad noise, probability .75 per sequence; RGB and original records immutable. Supervised desired positions come only from successful teacher labels, projected through each registered uniform horizon envelope; projected fraction is logged. No teacher action is an input.'
    tc['loss']='Motion-weighted masked normalized L1+0.1MSE; temporal residual .25; overlap target-residual consistency .1; original teacher max-arm delta supplies loss weight only'
    files=['exp3_oft_feedback_adapter_v0_167.py','train_exp3_oft_feedback_v0_167.py','serve_exp3_feedback_vla_v0_167.py','verify_exp3_feedback_training_v0_167.py','run_exp3_feedback_learning_v0_167.py','register_exp3_feedback_learning_v0_167.py','diagnose_exp3_training_feedback_v0_167.py']
    hashes=dict(tc['code_files_sha256']);hashes.update({str(repo/'tools'/f):sha(repo/'tools'/f) for f in files});tc['code_files_sha256']=hashes;tc['historical_parent_configuration_sha256']=sha(base/'training_configuration.json');emit(root/'training_configuration.json',tc)
    ec=json.loads((base/'evaluation_configuration.json').read_text());emit(root/'evaluation_configuration.json',ec);life.update(training_configuration=str(root/'training_configuration.json'),evaluation_configuration=str(root/'evaluation_configuration.json'),output=str(root/'execution-001'),lifecycle_entrypoint=str(repo/'tools/run_exp3_feedback_learning_v0_167.py'));emit(root/'lifecycle_configuration.json',life)
    emit(root/'method_manifest.json',dict(method_id=tc['method_id'],adapter_id=tc['action_adapter_id'],parent_method_id=tc['parent_method_id'],track='frozen_success_sequences_with_registered_proprio_augmentation',training_changes=['input proprio normalization','learned current-proprio skip path','proprio denoising augmentation','motion loss weighting'],hypothesis_source='training-only controlled proprio perturbation sensitivity, not heldout trajectories',hypothesis_summary=diagnosis['mean_absolute_target_sensitivity_per_input_delta'],no_teacher_inference=True,no_object_state_input=True,task_predicates_unchanged=True,heldout_unchanged=True,source_dataset_unchanged=True,denominator_per_variant=200,repeated_test_not_unseen_generalization=True,**ROBOT))
    emit(root/'lineage.json',dict(parent_registration=str(base),parent_files_sha256={str(base/f):sha(base/f) for f in ['training_configuration.json','evaluation_configuration.json','lifecycle_configuration.json','freeze_receipt.json']},diagnostic_files_sha256={str(p.resolve()):sha(p) for p in a.diagnostic.iterdir() if p.is_file()},feature_cache_manifest_sha256=sha(source_cache),new_output_only=True))
    emit(root/'freeze_receipt.json',dict(training_configuration_sha256=sha(root/'training_configuration.json'),evaluation_configuration_sha256=sha(root/'evaluation_configuration.json'),lifecycle_configuration_sha256=sha(root/'lifecycle_configuration.json'),code_files_sha256=hashes,registered_before_training=True,registered_before_new_evaluation=True,append_only=True));emit(root/'registration_execution_receipt.json',dict(command=[sys.executable,*sys.argv],timestamp=time.time(),configuration_sha256=sha(root/'training_configuration.json'),**ROBOT));print(json.dumps(dict(output=str(root),configuration_sha256=sha(root/'training_configuration.json'))))


if __name__=='__main__':main()
