"""Tables for the composed-scene manipulation study. Reads the recorded evaluation summaries and dataset manifests of the
scene study (--inputs scenes/: round2 and round1 of the final configuration; teacher_only = the first configuration,
third-person camera and teacher episodes only; fig7_export/collection_stats.json = the collection rounds) and writes
vla_results.tex (main text), vla_scenes.tex and vla_rounds.tex (appendix) plus facts/scene_study_facts.json. Edit this
generator, not the numeric cells.
Compact layouts (no interval column, one-decimal rates, short row and column names). The per-scene table keeps a short
task description per scene (Section 4.5 points to it for the task definitions) and the 8-character Objaverse id
prefixes. Files are written with CRLF line endings like the other generated tables."""

import json, math
from pathlib import Path
import argparse

_AP = argparse.ArgumentParser(description="scene-study tables")
_AP.add_argument(
    "--inputs",
    default=str(Path(__file__).resolve().parents[1] / "results"),
    help="recorded inputs (layout of analysis/results)",
)
_AP.add_argument(
    "--out",
    default=str(Path(__file__).resolve().parents[1] / "out"),
    help="output directory (tables/, figures/, facts/, sections/)",
)
_A = _AP.parse_args()
IN = Path(_A.inputs)
OUT = Path(_A.out)
RES = IN / "scenes"
TAB = OUT / "tables"
TAB.mkdir(parents=True, exist_ok=True)
ORDER = [
    "cabinet_cup",
    "cabinet1_box",
    "fridge_cup",
    "microwave_box",
    "drawer_cup",
    "drawer_two",
    "drawer_to_cabinet",
    "drawer_to_fridge",
    "laptop_cup",
    "trashcan_box",
]


def wilson(k, n, z=1.9599639845):
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return 100 * (c - h), 100 * (c + h)


def load(p):
    return json.load(open(p, encoding="utf-8"))


def write(name, lines):
    (TAB / name).write_text("\r\n".join(lines) + "\r\n", encoding="utf-8", newline="")


r2 = load(RES / "round2/eval_summary.json")["variants"]
r2s = load(RES / "round2/eval_summary_eval_seen.json")["variants"]
r1 = load(RES / "round1/eval_summary.json")["variants"]
r1s = load(RES / "round1/eval_summary_eval_seen.json")["variants"]
v19 = load(RES / "teacher_only/eval_summary.json")["variants"]
v19s = load(RES / "teacher_only/eval_summary_eval_seen.json")["variants"]
m2 = load(RES / "round2/dataset/manifest.json")
m1 = load(RES / "round1/dataset/manifest.json")
m19 = load(RES / "teacher_only/dataset/manifest.json")
cs = load(RES / "fig7_export/collection_stats.json")
# stage-1 counts of the teacher-only configuration (v19) are not in its summaries; derived from goals[0].ok of every episode.json:
V19_STAGE1 = {"eval": {"trained_vla": 28, "untrained_vla": 0}, "eval_seen": {"trained_vla": 29, "untrained_vla": 0}}


def n(v):
    return v["episodes"], v["passed"], v.get("stage1_reached")


te = sum(cs["collect20"][s]["episodes"] for s in ORDER)
tp = sum(cs["collect20"][s]["passed"] for s in ORDER)
ts = sum(cs["collect20"][s]["stage1"] for s in ORDER)
rows = [
    ("Scripted teacher", te, tp, ts),
    ("Untrained head, held-out", *n(r2["untrained_vla"])),
    ("Trained head, held-out", *n(r2["trained_vla"])),
    ("Trained head, seen", *n(r2s["trained_vla"])),
]
assert (
    (te, tp) == (320, 273)
    and n(r2["trained_vla"]) == (100, 11, 66)
    and n(r2["untrained_vla"]) == (40, 0, 1)
    and n(r2s["trained_vla"]) == (60, 8, 42)
)
GEN = "% Generated by analysis/tables/tables_scenes.py"
# ---------------------------------------------------------------- Table: conditions (main text)
L = [
    GEN + " from the recorded evaluation summaries (round 2). Edit the generator, not numeric cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\small",
    r"\setlength{\tabcolsep}{4pt}",
    r"\renewcommand{\arraystretch}{1.08}",
    r"\caption{\textbf{Manipulation in ten composed scenes.}",
    "An independent evaluator reads success from simulator state.",
    "Held-out and seen refer to initial states unseen or seen during data",
    "collection; the teacher row scores the assets, not a policy.",
    "The untrained head uses random initial weights.}",
    r"\label{tab:vla-results}",
    r"\begin{tabularx}{\linewidth}{@{}X r r S[table-format=2.1] r@{}}",
    r"\toprule",
    r"Condition & Episodes & Task success & {Rate (\%)} & Sub-goal 1 \\",
    r"\midrule",
]
for lab, ne, p, s1 in rows:
    pre = r"\rowcolor{acPale}" if lab == "Trained head, held-out" else ""
    L.append(pre + f"{lab} & {ne} & {p} & {100*p/ne:.1f} & {s1} \\\\")
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("vla_results.tex", L)
# ---------------------------------------------------------------- Table: per-scene tasks, assets and results (appendix)
DESC = {
    "cabinet_cup": "Cabinet (2-door) + cup: open far door, put cup inside",
    "cabinet1_box": "Cabinet (1-door) + box: open door, put box inside",
    "fridge_cup": "Refrigerator + cup: open door, put cup inside",
    "microwave_box": "Microwave + box: open door, put box inside",
    "drawer_cup": "Drawer + cup: open top drawer, put cup inside",
    "drawer_two": "Drawer + two cups: open top drawer, put both inside",
    "drawer_to_cabinet": r"Drawer$\to$cabinet + cup: move cup from open drawer to open cabinet, close drawer",
    "drawer_to_fridge": r"Drawer$\to$fridge + cup: move cup from open drawer to open fridge, close drawer",
    "laptop_cup": "Laptop + cup: close lid, put cup on top",
    "trashcan_box": "Trash can + box: lift lid, drop box inside",
}
ASSET = {
    "cabinet_cup": "46277, fae08c03",
    "cabinet1_box": "45623, 160d40d9",
    "fridge_cup": "10849, fae08c03",
    "microwave_box": "7310, 160d40d9",
    "drawer_cup": "46130, fae08c03",
    "drawer_two": "46130, fae08c03$\\times$2",
    "drawer_to_cabinet": "46130, 46277, fae08c03",
    "drawer_to_fridge": "46130, 10849, fae08c03",
    "laptop_cup": "11586, fae08c03",
    "trashcan_box": "11124, 160d40d9",
}


def c1(s):
    return s.split("/")[0]


L = [
    GEN + " from the recorded evaluation summaries and collection logs. Edit the generator, not numeric cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{3pt}",
    r"\renewcommand{\arraystretch}{1.05}",
    r"\caption{\textbf{Per-scene tasks, assets, and results.}",
    "Asset ids are PartNet-Mobility entries for articulated objects and",
    "8-character Objaverse id prefixes for rigid ones. Teacher counts are out of",
    "32 episodes. Trained-head columns show task successes and first-sub-goal",
    "counts on held-out states (10 episodes) and task successes on seen states",
    "(6); sg1: first sub-goal reached. Eight scenes include one distractor",
    "object.}",
    r"\label{tab:vla-scenes}",
    r"\begin{tabularx}{\linewidth}{@{}Z l r c r r@{}}",
    r"\toprule",
    r"Scene and task & Assets & \metrichead{Teach.\\/32} & \metrichead{Held-out\\task $\cdot$ sg1 /10} & \metrichead{Seen\\/6} & \metrichead{Untr.\\/4} \\",
    r"\midrule",
]
for s in ORDER:
    c = cs["collect20"][s]
    assert c["episodes"] == 32
    L.append(
        f"{DESC[s]} & {ASSET[s]} & {c['passed']} & {c1(r2['trained_vla']['per_scene'][s])}$\\cdot${c1(r2['trained_vla']['per_scene_stage1'][s])} & {c1(r2s['trained_vla']['per_scene'][s])} & {c1(r2['untrained_vla']['per_scene'][s])} \\\\"
    )
L.append(r"\midrule")
L.append(
    f"Total & & {tp}/320 & {r2['trained_vla']['passed']}/100 $\\cdot$ {r2['trained_vla']['stage1_reached']}/100 & {r2s['trained_vla']['passed']}/60 & {r2['untrained_vla']['passed']}/40 \\\\"
)
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("vla_scenes.tex", L)


# ---------------------------------------------------------------- Table: training configurations (appendix)
def ep(m):
    pm = m.get("episodes_per_mode") or {"teacher": m["episode_count"]}
    return pm.get("teacher", 0), pm.get("dagger", 0), m["frame_count"]


rounds = [
    (
        "3rd-person, teacher only",
        ep(m19),
        (v19["trained_vla"]["episodes"], v19["trained_vla"]["passed"], V19_STAGE1["eval"]["trained_vla"]),
        (v19s["trained_vla"]["episodes"], v19s["trained_vla"]["passed"], V19_STAGE1["eval_seen"]["trained_vla"]),
    ),
    ("+ wrist, crop; round 1", ep(m1), n(r1["trained_vla"]), n(r1s["trained_vla"])),
    ("Round 2 (all rollouts)", ep(m2), n(r2["trained_vla"]), n(r2s["trained_vla"])),
]
assert ep(m19) == (272, 0, 152469) and ep(m1) == (267, 82, 205129) and ep(m2) == (267, 397, 373031)
L = [
    GEN
    + " from the recorded dataset manifests and evaluation summaries (teacher-only configuration, rounds 1 and 2). Edit the generator, not numeric cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\small",
    r"\setlength{\tabcolsep}{3pt}",
    r"\renewcommand{\arraystretch}{1.08}",
    r"\caption{\textbf{Training configurations.}",
    "Each row is one trained head. Episodes count teacher demonstrations plus",
    "mixed rollouts after a dynamics filter. The first row used 4 held-out",
    "episodes per scene; the others use 10 held-out and 6 seen. Sg1: first",
    "sub-goal reached. Untrained heads complete 0 held-out episodes in every",
    "configuration.}",
    r"\label{tab:vla-rounds}",
    r"\begin{tabularx}{\linewidth}{@{}X r r r r r r r@{}}",
    r"\toprule",
    r" & \multicolumn{3}{c}{Training set} & \multicolumn{2}{c}{Held-out} & \multicolumn{2}{c}{Seen} \\",
    r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(l){7-8}",
    r"Config. & Teach. & Roll. & Frames & Task & Sg1 & Task & Sg1 \\",
    r"\midrule",
]
for i, (lab, (t, d, f), (hn, hp, hs), (sn, sp, ss)) in enumerate(rounds):
    pre = r"\rowcolor{acPale}" if i == 2 else ""
    L.append(pre + f"{lab} & {t} & {d} & \\num{{{f}}} & {hp}/{hn} & {hs}/{hn} & {sp}/{sn} & {ss}/{sn} \\\\")
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("vla_rounds.tex", L)
fail = [r for r in r2["trained_vla"]["rows"] if r["status"] != "passed"]
after = sum(r["stage1"] for r in fail)
facts = dict(
    heldout_failures=len(fail),
    failures_after_stage1=after,
    failures_before_stage1=len(fail) - after,
    teacher=dict(episodes=te, passed=tp, stage1=ts),
    dagger_recorded={
        t: dict(episodes=sum(cs[t][s]["episodes"] for s in ORDER), passed=sum(cs[t][s]["passed"] for s in ORDER))
        for t in ("dagger20", "dagger20r2")
    },
    round2_dataset={
        k: m2[k]
        for k in (
            "episode_count",
            "frame_count",
            "episodes_per_mode",
            "failed_episodes_included",
            "policy_executed_ticks",
        )
    },
    wilson=dict(
        trained_heldout=wilson(11, 100),
        untrained_heldout=wilson(0, 40),
        trained_seen=wilson(8, 60),
        teacher=wilson(tp, te),
    ),
)
(OUT / "facts").mkdir(parents=True, exist_ok=True)
(OUT / "facts" / "scene_study_facts.json").write_text(json.dumps(facts, indent=1), encoding="utf-8")
print("scene tables written; teacher", tp, "/", te, "held-out", r2["trained_vla"]["passed"], "/100")
