"""Table of the single-asset manipulation study (Exp3): the appendix reports all twenty trained tasks, the ten single-asset
tasks and the ten composed scenes. Source: single_asset/per_asset_results.csv (per-asset results of the registered
single-asset run, policy/single_asset/: 1,000 teacher episodes, paired 2x200 held-out evaluation). Writes
<out>/tables/vla_single_asset.tex. Asset names match the panel titles of the learning figure."""

import csv, os
from pathlib import Path

import argparse

_AP = argparse.ArgumentParser(description="single-asset study table")
_AP.add_argument(
    "--inputs",
    default=str(Path(__file__).resolve().parents[1] / "results"),
    help="recorded inputs (layout of analysis/results)",
)
_AP.add_argument(
    "--out",
    default=str(Path(__file__).resolve().parents[1] / "out"),
    help="output directory (tables/, figures/, facts/, sections/)",
)
_A = _AP.parse_args()
IN = Path(_A.inputs)
OUT = Path(_A.out)
TAB = OUT / "tables"
TAB.mkdir(parents=True, exist_ok=True)
rows = list(csv.DictReader(open(IN / "single_asset/per_asset_results.csv", encoding="utf-8")))
NAME = {
    "rigid_00_bottle": ("Bottle", "push into region"),
    "rigid_compact_box_cf109672": ("Box", "push into region"),
    "rigid_compact_camera_9f360f3c": ("Camera", "push into region"),
    "rigid_compact_clock_ddb96318": ("Clock", "push into region"),
    "rigid_compact_display_67ea5509": ("Display", "push into region"),
    "articulated_01_microwave": ("Microwave", "close door"),
    "articulated_02_storage_45526": ("Storage 02 (45526)", "close door"),
    "articulated_03_storage_45638": ("Storage 03 (45638)", "close door"),
    "articulated_04_storage_46889": ("Storage 04 (46889)", "close door"),
    "articulated_drawer_46236": ("Drawer (46236)", "close drawer"),
}
ORDER = [
    "rigid_00_bottle",
    "rigid_compact_box_cf109672",
    "rigid_compact_camera_9f360f3c",
    "rigid_compact_clock_ddb96318",
    "rigid_compact_display_67ea5509",
    "articulated_01_microwave",
    "articulated_02_storage_45526",
    "articulated_03_storage_45638",
    "articulated_04_storage_46889",
    "articulated_drawer_46236",
]
by = {r["asset_id"]: r for r in rows}
assert sorted(by) == sorted(ORDER), sorted(by)
tr = sum(int(by[a]["trained_success"]) for a in ORDER)
un = sum(int(by[a]["untrained_success"]) for a in ORDER)
assert (tr, un) == (114, 1), (tr, un)
L = [
    "% Generated by analysis/tables/tables_exp3.py from single_asset/per_asset_results.csv (Exp3). Edit the generator, not numeric cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\small",
    r"\setlength{\tabcolsep}{4pt}",
    r"\renewcommand{\arraystretch}{1.08}",
    r"\caption{\textbf{Ten single-asset tasks.} Successes out of 20 held-out episodes per task for the same head before and after training; blocked: initial states without an episode record in either condition, counted as failures.}",
    r"\label{tab:vla-assets}",
    r"\begin{tabularx}{\linewidth}{@{}X l r r r@{}}",
    r"\toprule",
    r"Asset & Task & Untrained & Trained & Blocked \\",
    r"\midrule",
]
for grp, keys in (("Rigid objects", ORDER[:5]), ("Articulated assets", ORDER[5:])):
    L.append(r"\addlinespace[2pt]\rowcolor{acPale}\multicolumn{5}{@{}l}{\tablegroup{" + grp + r"}} \\")
    for a in keys:
        r = by[a]
        n, t = NAME[a]
        b = int(r["trained_blocked"])
        L.append(
            f"{n} & {t} & {int(r['untrained_success'])} & {int(r['trained_success'])} & {b if b else '--'} " + r"\\"
        )
L += [
    r"\midrule",
    f"All ten tasks & & {un}/200 & {tr}/200 & 5 " + r"\\",
    r"\bottomrule",
    r"\end{tabularx}",
    r"\end{table}",
]
(TAB / "vla_single_asset.tex").write_text("\r\n".join(L) + "\r\n", encoding="utf-8", newline="")
print("written", TAB / "vla_single_asset.tex", tr, un)
