"""Main comparison table (Table 1) and the three tables it shares a generator with. Reads recorded evidence only
(paths relative to --inputs):
- campaign/evidence_v2_20260920-181120.json     main campaign (full-RGB protocol, formal-code-009), from export_paper_evidence.py
- campaign/subset200_from_formal013.json        read-only recount of the verified per-case records on the registered
                                                200-input subset (receipt with sha256)
- campaign/table1_extra_metrics_20260922.json   articulated passes, E2E and worker minutes of the main campaign's records
- campaign/exp2_union_summary.json              cluttered-image experiment, union of the two detection sources
- development/evidence.json                     development runs under the target-assisted protocol (v0.x)
- external/aggregate_all_*.json                 newest output of evaluation/aggregate/aggregate_external.py
- clean_timing/clean_timing_summary_*.json      newest output of evaluation/timing/summarize_clean_timing.py
- external/api_cost_official_*.json             newest output of evaluation/api_cost/api_cost_official.py
Writes <out>/tables/main_comparison.tex, development_single.tex, multi_object.tex, resource_metrics.tex and
<out>/facts/comparison_facts.json. Edit this generator, not the numeric cells.
Table 1 keeps the method x metric layout (unmeasured cells blank) without a Wilson-interval column; the other three
tables use the compact layouts of the manuscript."""

import json, math, os
from pathlib import Path
import argparse

_AP = argparse.ArgumentParser(description="Table 1, resource table and the development tables")
_AP.add_argument(
    "--inputs",
    default=str(Path(__file__).resolve().parents[1] / "results"),
    help="recorded inputs (layout of analysis/results)",
)
_AP.add_argument(
    "--out",
    default=str(Path(__file__).resolve().parents[1] / "out"),
    help="output directory (tables/, figures/, facts/, sections/)",
)
_A = _AP.parse_args()
IN = Path(_A.inputs)
OUT = Path(_A.out)
TAB = OUT / "tables"
TAB.mkdir(parents=True, exist_ok=True)


def load(p):
    return json.load(open(p, encoding="utf-8"))


def write(name, lines):
    (TAB / name).write_text("\r\n".join(lines) + "\r\n", encoding="utf-8", newline="")


def wilson(k, n, z=1.9599639845):
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return 100 * (c - h), 100 * (c + h)


def pct(k, n):
    return f"{100*k/n:.2f}"


E2 = load(IN / "campaign/evidence_v2_20260920-181120.json")
S200 = load(IN / "campaign/subset200_from_formal013.json")
E1 = load(IN / "development/evidence.json")
U = load(IN / "campaign/exp2_union_summary.json")
assert (
    U["complete"]
    and (U["union"]["localized"], U["union"]["physical_passes"], U["union"]["all_object_images"]) == (172, 162, 15)
    and U["construction_pass_rate_over_predictions"]["union"] == dict(records=575, physical_pass=563)
)
x1 = E2["main_campaign"]["exp1"]
x2 = E2["main_campaign"]["exp2"]
ref = x2["reference_evaluation"]
assert (
    x1["denominator"] == 2000
    and x1["physical_pass"] == 1703
    and S200["subset_n"] == 200
    and S200["subset_physical_pass"] == 167
)
assert S200["total_physical_pass"] == 1703 and S200["no_reference_boxes_or_masks"] is True
assert (
    (ref["localized"], ref["physical_passes"], ref["all_object_images"]) == (105, 100, 13)
    and x2["physical_pass"] == 283
    and x2["denominator"] == 289
)
BS = "\\"


def mh(a, b):
    return r"\metrichead{" + a + BS + BS + b + "}"


GEN = "% Generated by analysis/tables/tables_comparison.py. Edit the generator, not numeric cells."
# ---------------------------------------------------------------- Table 1: full-RGB comparison, methods x metrics
# Columns: export, native/adapted pass, articulated share, per-input timing and resource cells. The AffordCraft pass cells
# come from the verified per-case records of the main campaign (extra-metrics receipt below) and the evidence file; the
# campaign's own timing/resource cells carry a dagger (a throughput run, not an exclusive-device measurement) and are
# replaced by the clean timing run when its summary exists (below).
X = load(IN / "campaign/table1_extra_metrics_20260922.json")
XA = X["all2000"]
XS = X["subset200"]
assert (XA["n"], XA["passes"], XS["n"], XS["passes"]) == (2000, 1703, 200, 167)
T = x1["timing_seconds"]
RES = E2["main_campaign"]["resources"]
assert abs(XA["e2e_median"] - T["e2e_median"]) < 0.05 and abs(XA["e2e_p95"] - T["e2e_p95"]) < 0.1
exports = x1["denominator"] - x1["outcome_counts"]["no_structured_export"]
assert set(x1["outcome_counts"]) == {"physical_pass", "no_structured_export"} and exports == 1703
exports_s = S200["subset_n"] - sum(S200["subset_failure_status"].values())
assert exports_s == 167
peak = RES["peak_gpu_memory_mib_per_worker_tree_max"] / 1024
# External rows: read from the newest aggregate written by evaluation/aggregate/aggregate_external.py. A row is filled
# only when its run is complete: every input has a
# terminal verdict and none is blocked by infrastructure (pending == 0 and infra_blocked == 0); otherwise it stays blank.
# Rates use the full registered denominator. Methods without physical parameters (single-mesh generators) have no
# native condition; their timing columns follow the adapted path (double dagger).
import glob as _glob

EXT_FILES = sorted(
    _glob.glob(str(Path(os.environ.get("AFFORDCRAFT_EXT_DIR") or (IN / "external")) / "aggregate_all_*.json"))
)  # AFFORDCRAFT_EXT_DIR: dry runs only
EXT = load(EXT_FILES[-1])["methods"] if EXT_FILES else {}
EXT_SRC = Path(EXT_FILES[-1]).name if EXT_FILES else "none"
# Clean timing run (evaluation/timing): one worker per exclusive RTX 5090 for every method and stage (the PhysX-Omni
# geometry stage, 91 GiB peak, on an RTX PRO 6000), a 32-input sample of the registered subset, the same code, weights and
# settings as the registered runs, gates with an empty geometry cache. When its summary exists it supplies every per-input
# timing/resource cell (Table 1 and the resource table); pass rates stay those of each row's registered run, so worker
# minutes per pass = clean mean seconds per input (failed inputs included) / the row's pass rate. Peak = nvidia-smi device
# memory of the worker's GPU. AffordCraft: the cold regime (geometry cache as at the start of the formal campaign).
# AFFORDCRAFT_CLEAN_DIR: dry runs; AFFORDCRAFT_CLEAN_PARTIAL=1 accepts an unfinished summary (dry runs only).
CLEAN_FILES = sorted(
    _glob.glob(
        str(Path(os.environ.get("AFFORDCRAFT_CLEAN_DIR") or (IN / "clean_timing")) / "clean_timing_summary_*.json")
    )
)
CLEAN = load(CLEAN_FILES[-1]) if CLEAN_FILES else None
CLEAN_SRC = Path(CLEAN_FILES[-1]).name if CLEAN_FILES else None
OURS_REGIME = "warm"  # the reuse regime (geometry of the library entries built once) is the main number; cold goes to the appendix
CO = ((CLEAN or {}).get("ours") or {}).get(OURS_REGIME)
CLEAN_OURS = bool(CO) and (CO.get("n") == CLEAN["sample"]["n"] or os.environ.get("AFFORDCRAFT_CLEAN_PARTIAL") == "1")


def clean_peak(mid):
    s = CLEAN["external"][mid]
    lw = s.get("lane_walls") or {}
    v = (
        [(d.get("monitor") or {}).get("peak_gib") for k in ("representation", "geometry") for d in lw.get(k, [])]
        if mid == "physx-omni-v0.1"
        else [lw.get("monitor_peak_gib")]
    )
    v = [x for x in v if x]
    return max(v) if v else None


def clean_ext(mid):
    """(timing, stage medians) of one external method from the clean run, or None."""
    if not CLEAN_OURS or mid not in CLEAN["external"]:
        return None
    s = CLEAN["external"][mid]
    t = dict(s["timing"])
    t["peak_gib_max"] = max([x for x in (clean_peak(mid), t.get("peak_gib_max")) if x] or [None])
    t["clean_worker"] = s.get("clean_worker") or {}
    t["gated"] = s.get("gated")
    return t, s["stage_medians"]


def clean_fact_timing(tt, t, c, n):
    """the registered run's timing dict with every timing value replaced by the clean run's (same keys as the aggregate)."""
    w = tt["clean_worker"]
    r = dict(t)
    for kk in (
        "stage1_median_s",
        "geometry_median_s",
        "native_gate_median_s",
        "adapted_materialize_median_s",
        "e2e_native_median_s",
        "e2e_native_p95_s",
        "e2e_adapted_median_s",
        "e2e_adapted_p95_s",
    ):
        r[kk] = tt.get(kk)
    r.update(
        e2e_native_mean_s=w.get("native_mean_s"),
        e2e_adapted_mean_s=w.get("adapted_mean_s"),
        worker_minutes_per_native_pass=(
            round(tt["e2e_native_median_s"] / 60 / (c["native_pass"] / n), 1)
            if tt.get("e2e_native_median_s") and c["native_pass"]
            else None
        ),
        worker_minutes_per_adapted_pass=(
            round(tt["e2e_adapted_median_s"] / 60 / (c["adapted_pass"] / n), 1)
            if tt.get("e2e_adapted_median_s") and c["adapted_pass"]
            else None
        ),
        worker_minutes_per_native_pass_mean=(
            round(w["native_mean_s"] / 60 / (c["native_pass"] / n), 1)
            if w.get("native_mean_s") and c["native_pass"]
            else None
        ),
        worker_minutes_per_adapted_pass_mean=(
            round(w["adapted_mean_s"] / 60 / (c["adapted_pass"] / n), 1)
            if w.get("adapted_mean_s") and c["adapted_pass"]
            else None
        ),
        cost_basis="median time per input / pass rate of the row",
        peak_gib_max=tt.get("peak_gib_max"),
        source=CLEAN_SRC,
        gated=tt.get("gated"),
        scope="clean timing run (32-input sample); pass rates of the registered run",
    )
    return r


CAP_T1 = (
    r"Per-input columns: clean timing run on 32 subset inputs with one RTX 5090 per worker, \method\ with its library\textquoteright s collision geometry built once (Appendix~\ref{app:resources}). "
    if CLEAN_OURS
    else r"$\dagger$: recorded by the formal campaign, a throughput run with two workers per A100 and a geometry cache, not an exclusive-device measurement; "
)
DDG = r"$^\ddagger$"
# API cost at the providers' official list prices from the recorded token counts (api_cost_official_*.json),
# and the section mark for the two API routes whose per-input times come from their own runs (not the clean timing run).
API_FILES = sorted(_glob.glob(str(IN / "external/api_cost_official_*.json")))
API_COST = load(API_FILES[-1]) if API_FILES else {}


def api_cell(mid):
    v = (API_COST.get(mid) or {}).get("usd_per_input_mean_upper") or (API_COST.get(mid) or {}).get("usd_per_input_mean")
    if v is None:
        return None
    return f"{v:.2f}" if v >= 1 else (f"{v:.3f}" if v >= 0.001 else f"{v:.4f}")


API_TIMED = ("articulate-anything-v0.1", "gpt6-astra-agent-v0.1")
# The per-input tail column is the share of the timed inputs whose asset passes within BUDGET_S seconds of wall
# time (clean timing rows; the API routes' own rows); P90 (nearest rank) is kept in the facts only.
BUDGET_S = 300


def q_nearest(v, q):
    v = sorted(v)
    return v[max(math.ceil(q * len(v)), 1) - 1] if v else None


def within_budget(rows, tk, pk, b=BUDGET_S):
    return (
        100.0 * sum(1 for r in rows if r.get(pk) and r.get(tk) is not None and r[tk] <= b) / len(rows) if rows else None
    )


def api_tag(mid, tag):
    if mid not in API_TIMED:
        return tag
    return r"$^{\ddagger\S}$" if tag == DDG else r"$^\S$"


def ext_cells(mid, track):
    """(cells, facts) of one external row; blank cells while the run is incomplete."""
    m = EXT.get(mid)
    s = (m or {}).get(track)
    if not s:
        return [""] * (NC - 2), dict(status="no aggregate")
    c = s["counts"]
    t = s["timing"]
    n = s["denominator"]
    fact = dict(
        aggregate=EXT_SRC,
        track=track,
        n=n,
        pending=c["pending"],
        blocked=c["infra_blocked"],
        export=c["export"],
        native_pass=c["native_pass"],
        adapted_pass=c["adapted_pass"],
        native_pass_articulated=c["native_pass_articulated"],
        adapted_pass_articulated=c["adapted_pass_articulated"],
        native_applies=t["native_applies"],
        timing=t,
    )
    if (c["pending"] > 0 or c["infra_blocked"] > 0) and not SIM:
        return [""] * (NC - 2), dict(
            fact, status="incomplete: %d pending, %d blocked" % (c["pending"], c["infra_blocked"])
        )
    ex = pct(c["export"], n)
    if t["native_applies"]:
        nat = pct(c["native_pass"], n)
        art = pct(c["native_pass_articulated"], n)
        e2e, p95, wm, tag = t["e2e_native_median_s"], t["e2e_native_p95_s"], t["worker_minutes_per_native_pass"], ""
    else:
        nat = "{--}"
        art = pct(c["adapted_pass_articulated"], n)
        e2e, p95, wm, tag = (
            t["e2e_adapted_median_s"],
            t["e2e_adapted_p95_s"],
            t["worker_minutes_per_adapted_pass"],
            DDG,
        )  # braces: the Native column is a siunitx S column
    ada = pct(c["adapted_pass"], n)
    pk = t.get("peak_gib_max")
    ct = clean_ext(mid)
    if ct:  # clean timing run: timing/resource cells from the clean run, pass rates from this row's registered run
        tc = clean_fact_timing(ct[0], t, c, n)
        fact = dict(fact, timing=tc, timing_campaign=t)
        nk = "native" if t["native_applies"] else "adapted"
        e2e, p95, wm, pk = (
            tc[f"e2e_{nk}_median_s"],
            tc[f"e2e_{nk}_p95_s"],
            tc[f"worker_minutes_per_{nk}_pass"],
            tc["peak_gib_max"],
        )
    tag = api_tag(mid, tag)
    if (
        mid in API_TIMED and not ct and e2e is not None
    ):  # median rule for the API rows (min/pass = median time / pass rate)
        kk = c["native_pass"] if t["native_applies"] else c["adapted_pass"]
        wm = round(e2e / 60 / (kk / n), 1) if kk else None
    tk, pk_ = ("e2e_native_seconds", "native_pass") if t["native_applies"] else ("e2e_adapted_seconds", "adapted_pass")
    brows = (
        CLEAN["external"][mid]["rows"] if ct else s["rows"]
    )  # rows of the per-input columns: the clean sample, or the API run itself
    w5 = within_budget(brows, tk, pk_)
    p90 = q_nearest([r[tk] for r in brows if r.get(tk) is not None], 0.90)
    fact = dict(
        fact, within_5min_pct=w5, within_5min_rows=len(brows), e2e_p90_s=p90, e2e_p95_s_table_until_20260925=p95
    )
    cells = [
        ex,
        nat,
        ada,
        art,
        (f"{e2e:.1f}{tag}" if e2e is not None else ""),
        (f"{w5:.1f}{tag}" if w5 is not None else ""),
        (f"{wm:.1f}{tag}" if wm is not None else ""),
        (f"{pk:.1f}" if pk else ""),
    ]
    return cells, dict(fact, status="complete")


# Track choice: the 2,000-input numbers of every method whose 2,000-input run is complete are printed, never its
# 200-input numbers: each row lists its tracks in order of preference; the first complete one is printed and
# N follows it; while none is complete the first track stays blank. PhysX-Omni has no 200-input fallback (its 2,000-input
# run is the registered one); PartCrafter (part count from a remote VLM) and the two API routes have no 2,000-input run.
# AFFORDCRAFT_SIMULATE_COMPLETE=1 (dry runs into a scratch --out only): every row prints its preferred track from the
# partial numbers so the mixed-track layout and wording can be checked before the runs finish.
SIM = os.environ.get("AFFORDCRAFT_SIMULATE_COMPLETE") == "1"
TRACK_N = {"full2000": r"\num{2000}", "subset200": "200"}
ROWS = [
    ("group", "Generative reconstruction or mesh generation from one RGB image"),
    ("PhysX-Anything", "physx-anything-v0.1", ["full2000", "subset200"]),
    ("PhysX-Omni", "physx-omni-v0.1", ["full2000"]),
    ("PAct", "pact-v0.1", ["full2000", "subset200"]),
    ("PartCrafter", "partcrafter-v0.1", ["full2000", "subset200"]),
    ("TRELLIS.2", "trellis2-4b-v0.1", ["full2000", "subset200"]),
    ("group", "Library retrieval or general agent"),
    ("Articulate-Anything", "articulate-anything-v0.1", ["subset200"]),
    ("GPT-6 Astra agent", "gpt6-astra-agent-v0.1", ["subset200"]),
]


def track_complete(mid, track):
    s = (EXT.get(mid) or {}).get(track)
    return bool(s) and s["counts"]["pending"] == 0 and s["counts"]["infra_blocked"] == 0


def choose_track(mid, tracks):
    return tracks[0] if SIM else next((t for t in tracks if track_complete(mid, t)), tracks[0])


CHOSEN = {}
NC = 10
L = [
    GEN
    + " Sources: campaign/evidence_v2_20260920-181120.json (main campaign, formal-code-009), campaign/subset200_from_formal013.json, campaign/table1_extra_metrics_20260922.json; external rows: "
    + EXT_SRC
    + " (complete runs only).",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{2pt}",
    r"\renewcommand{\arraystretch}{1.08}",
]
L.append(
    r"\caption{\textbf{Single-photograph construction from the full image.} Native: passes the physical gate as delivered; Adapted: passes after our common physical adaptation; Artic.: accepted with a movable joint. "
    + CAP_T1
    + r"$\ddagger$: adapted path (no physical parameters); $\S$: timed in the method\textquoteright s own API run; --: not applicable; blank: not measured.}"
)
L.append(r"\label{tab:main}")
L.append(
    r"\begin{tabularx}{\linewidth}{@{}Z r S[table-format=2.2] S[table-format=2.2] c S[table-format=2.2] r r r r@{}}"
)
L.append(r"\toprule")
L.append(r" &  & \multicolumn{4}{c}{Export and physical gate (\%)} & \multicolumn{4}{c}{Per input} \\")
L.append(r"\cmidrule(lr){3-6}\cmidrule(l){7-10}")
L.append(
    "Method & $N$ & {Export} & {Native} & Adapted & {Artic.} & "
    + mh("Median", "time (s)")
    + " & "
    + mh("Pass in", r"5 min (\%)")
    + " & "
    + (mh("GPU min", "per pass") if CLEAN_OURS else mh("Worker", "min/pass"))
    + " & "
    + mh("Peak", "GiB")
    + r" \\"
)
L.append(r"\midrule")
facts = []
for r in ROWS:
    if r[0] == "group":
        L.append(r"\rowcolor{acPale}\multicolumn{" + str(NC) + r"}{c}{\tablegroup{" + r[1] + r"}} \\")
        continue
    name, mid, tracks = r
    track = choose_track(mid, tracks)
    CHOSEN[mid] = track
    n = TRACK_N[track]
    cells, fact = ext_cells(mid, track)
    L.append(f"{name} & {n} & " + " & ".join(cells) + r" \\")
    facts.append(dict(method=name, planned_inputs=n, method_id=mid, tracks=tracks, **fact))
L.append(r"\addlinespace[1pt]\midrule")
k, n = x1["physical_pass"], x1["denominator"]
ks, ns = S200["subset_physical_pass"], S200["subset_n"]
DG = r"$^\dagger$"
O1 = dict(
    e2e=T["e2e_median"],
    p95=T["e2e_p95"],
    wmin=XA["gpu_min_per_pass"],
    peak=peak,
    scope="throughput run of the formal campaign (dagger)",
)
O2 = dict(
    e2e=XS["e2e_median"],
    p95=XS["e2e_p95"],
    wmin=XS["gpu_min_per_pass"],
    peak=peak,
    scope="throughput run of the formal campaign (dagger)",
)
if CLEAN_OURS:  # the clean timing run replaces the campaign cells (no dagger); pass rates of the row
    DG = ""
    cpk = max([(x.get("monitor") or {}).get("peak_gib") or 0 for x in CO["shards"]] or [0]) or peak
    sc = f"clean timing run ({OURS_REGIME} geometry cache), 32-input sample, one worker per exclusive RTX 5090; minutes per pass = clean median seconds per input / pass rate of the row (the cost of an accepted asset at the median)"
    O1 = dict(
        e2e=CO["e2e_median"],
        p95=CO["e2e_p95"],
        wmin=round(CO["e2e_median"] / 60 / (k / n), 1),
        wmin_mean=round(CO["e2e_mean"] / 60 / (k / n), 1),
        peak=cpk,
        scope=sc,
        campaign=dict(e2e=T["e2e_median"], p95=T["e2e_p95"], wmin=XA["gpu_min_per_pass"], peak=peak),
    )
    O2 = dict(
        e2e=CO["e2e_median"],
        p95=CO["e2e_p95"],
        wmin=round(CO["e2e_median"] / 60 / (ks / ns), 1),
        wmin_mean=round(CO["e2e_mean"] / 60 / (ks / ns), 1),
        peak=cpk,
        scope=sc,
        campaign=dict(e2e=XS["e2e_median"], p95=XS["e2e_p95"], wmin=XS["gpu_min_per_pass"], peak=peak),
    )
assert CLEAN_OURS, "the per-input columns of Table 1 need the clean timing run"
for _o, _reg in ((O1, OURS_REGIME), (O2, OURS_REGIME)):
    _rw = CLEAN["ours"][_reg]["rows"]
    _o.update(
        w5=within_budget(_rw, "total_wall_seconds", "physical_pass"),
        p90=q_nearest([r["total_wall_seconds"] for r in _rw], 0.90),
    )
_rc = CLEAN["ours"]["cold"]["rows"]
OURS_COLD = dict(
    w5=within_budget(_rc, "total_wall_seconds", "physical_pass"),
    p90=q_nearest([r["total_wall_seconds"] for r in _rc], 0.90),
)


def ours(label, ncell, ex, kk, nn, art, o):
    return (
        label
        + f" & {ncell} & "
        + pct(ex, nn)
        + " & "
        + pct(kk, nn)
        + " & -- & "
        + pct(art, nn)
        + " & "
        + f"{o['e2e']:.1f}{DG} & {o['w5']:.1f}{DG} & {o['wmin']:.1f}{DG} & {o['peak']:.1f}{DG}"
        + r" \\"
    )


L.append(
    r"\rowcolor{acPale}" + ours(r"\textbf{\method\ (ours)}", r"\num{2000}", exports, k, n, XA["articulated_passes"], O1)
)
# the 200-input subset row of AffordCraft is not printed; its 167/200 stays in the text (Section 4.2) and in the facts below
facts += [
    dict(
        method="AffordCraft",
        input="RGB + text",
        planned_inputs="2,000",
        export=exports,
        native=dict(k=k, n=n, rate=100 * k / n, ci=wilson(k, n)),
        adapted="not applicable",
        articulated=XA["articulated_passes"],
        e2e_median_s=O1["e2e"],
        e2e_p95_s=O1["p95"],
        within_5min_pct=O1["w5"],
        e2e_p90_s=O1["p90"],
        cold=OURS_COLD,
        worker_min_per_pass=O1["wmin"],
        worker_min_per_pass_mean=O1.get("wmin_mean"),
        peak_gib=O1["peak"],
        timing_scope=O1["scope"],
        timing_campaign=O1.get("campaign"),
    ),
    dict(
        method="AffordCraft, shared 200-input subset",
        input="RGB + text",
        planned_inputs="200",
        export=exports_s,
        native=dict(k=ks, n=ns, rate=100 * ks / ns, ci=wilson(ks, ns)),
        adapted="not applicable",
        articulated=XS["articulated_passes"],
        e2e_median_s=O2["e2e"],
        e2e_p95_s=O2["p95"],
        within_5min_pct=O2["w5"],
        e2e_p90_s=O2["p90"],
        worker_min_per_pass=O2["wmin"],
        worker_min_per_pass_mean=O2.get("wmin_mean"),
        peak_gib=O2["peak"],
        timing_scope=O2["scope"],
        timing_campaign=O2.get("campaign"),
    ),
]
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("main_comparison.tex", L)
# ---------------------------------------------------------------- development table (appendix; target-assisted v0.x evidence)
H = E1["historical"]
specs = [
    ("baseline", "Single-candidate + adaptation"),
    ("vlm_v02", "+ scale estimation"),
    ("vlm_v03", "+ selected scale hypotheses"),
    ("top5", "Multimodal candidate selection"),
    ("top5_art", "+ articulation adapter"),
]
assert [H[kk]["success"] for kk, _ in specs] == [685, 1043, 1172, 887, 1203]
L = [
    GEN + " Source: development/evidence.json (development runs, target-assisted protocol).",
    r"\begin{table}[t]",
    r"\centering",
    r"\small",
    r"\setlength{\tabcolsep}{4pt}",
    r"\renewcommand{\arraystretch}{1.08}",
]
L += [
    r"\caption{\textbf{Development configurations (target-assisted protocol).}",
    "Each row received the registered target region and category label.",
    "All 2,000 inputs are retained. Rows are successive development versions,",
    "not one-factor ablations; the last row reuses the retrieval above it and",
    "adds the articulation adapter.}",
]
L.append(r"\label{tab:development}")
L.append(r"\begin{tabularx}{\linewidth}{@{}X r S[table-format=2.2]@{}}")
L.append(r"\toprule")
L.append(r"Configuration & Pass / 2,000 & {Rate (\%)} \\")
L.append(r"\midrule")
dev = []
for i, (key, title) in enumerate(specs):
    if i == 0:
        L.append(r"\rowcolor{acPale}\multicolumn{3}{c}{\tablegroup{Single-candidate construction}} \\")
    if i == 3:
        L.append(r"\addlinespace[1pt]")
        (
            L.append(r"\rowcolor{acPale}\multicolumn{3}{c}{\tablegroup{Candidate selection and repair}} \\")
            if i == 3
            else None
        )
    d = H[key]
    kk, nn = d["success"], d["total"]
    lo, hi = d["ci"]["lower"], d["ci"]["upper"]
    L.append(f"{title} & " + r"\num{" + str(kk) + "}" + f' & {100*d["rate"]:.2f} ' + r"\\")
    dev.append(dict(key=key, title=title, k=kk, n=nn, rate=d["rate"], ci=[lo, hi]))
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("development_single.tex", L)
# ---------------------------------------------------------------- cluttered development table (appendix; recorded target-assisted values)
L = [
    GEN
    + " Source: development/evidence.json (development runs on annotation-backed objects, target-assisted protocol).",
    r"\begin{table}[t]",
    r"\centering",
    r"\small",
    r"\setlength{\tabcolsep}{4pt}",
    r"\renewcommand{\arraystretch}{1.08}",
]
L += [
    r"\caption{\textbf{Cluttered images under the target-assisted protocol.}",
    "Three development configurations on the 237 annotated instances, each given",
    r"the registered target crop. Object counts use $N{=}237$; image counts use",
    r"$N{=}50$. These rates measure construction from a located target and are",
    r"not comparable with the detection-based result of Section~\ref{sec:multi-results}.}",
]
L.append(r"\label{tab:multi-object}")
L.append(r"\begin{tabularx}{\linewidth}{@{}X r r S[table-format=2.1] r@{}}")
L.append(r"\toprule")
L.append(r"Configuration & Exported & Passed & {Rate (\%)} & " + mh("All-pass", "images") + r" \\")
L.append(r"\midrule")
mo = []
for key, title in [
    ("crop_only", "Crop-only control"),
    ("object_centric", "Category-conditioned"),
    ("top5_vlm", "Multimodal selection"),
]:
    d = E1["exp2"][key]
    ex = d["metrics"]["asset_emitted"]["raw"]
    p = d["metrics"]["sim_ready_only"]["raw"]
    im = d["all_objects_physics_only"]
    pre = r"\rowcolor{acPale}" if key == "object_centric" else ""
    L.append(f'{pre}{title} & {ex["success"]} & {p["success"]} & {100*p["rate"]:.1f} & {im["success"]} ' + r"\\")
    mo.append(
        dict(
            key=key,
            exported=ex["success"],
            passed=p["success"],
            rate=p["rate"],
            ci=[p["lower"], p["upper"]],
            all_object_images=im["success"],
        )
    )
assert [m["passed"] for m in mo] == [29, 236, 191] and [m["all_object_images"] for m in mo] == [0, 49, 19]
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("multi_object.tex", L)
# ---------------------------------------------------------------- resource table: stage timing per method
# One column per compared method. External columns are filled from the aggregate only when the run is complete (same
# rule as Table 1); stage medians are the per-case wall seconds each stage process recorded. Row mapping per method:
#   perception = our grounding+retrieval+selection | PhysX-*: VLM/representation stage | PAct: mask adapter | PartCrafter:
#   VLM part count | TRELLIS.2: preprocessing | Articulate-Anything: retrieval;  generation = our adaptation |
#   decoder/geometry/export stages;  adaptation = our common adaptation of the delivered asset (external rows only);
#   validation = physical gate seconds (native path where it applies, else adapted).
RCOLS = [
    ("Afford-\\Craft", None),
    ("PhysX-\\Anything", "physx-anything-v0.1"),
    ("PhysX-\\Omni", "physx-omni-v0.1"),
    ("PAct", "pact-v0.1"),
    ("Part-\\Crafter", "partcrafter-v0.1"),
    ("TRELLIS.2", "trellis2-4b-v0.1"),
    ("Articulate-\\Anything", "articulate-anything-v0.1"),
    ("GPT\\agent", "gpt6-astra-agent-v0.1"),
]


def rsum(sm, *keys):
    v = [sm.get(k) for k in keys if sm.get(k) is not None]
    return sum(v) if v else None


def rcol(mid):
    m = EXT.get(mid)
    sub = (m or {}).get(CHOSEN.get(mid, "subset200"))  # same track as the method's Table 1 row
    if not sub or ((sub["counts"]["pending"] > 0 or sub["counts"]["infra_blocked"] > 0) and not SIM):
        return {}
    sm = sub["stage_medians"]
    t = sub["timing"]
    c = sub["counts"]
    nat = t["native_applies"]
    ct = clean_ext(mid)
    if ct:
        t = clean_fact_timing(ct[0], t, c, sub["denominator"])
        sm = ct[1]  # clean timing run, pass rates of the registered run
    perc = {
        "physx-anything-v0.1": sm.get("vlm_seconds"),
        "physx-omni-v0.1": sm.get("representation_seconds"),
        "pact-v0.1": sm.get("adapter_total"),
        "partcrafter-v0.1": sm.get("vlm_seconds"),
        "trellis2-4b-v0.1": sm.get("preprocess_seconds"),
        "articulate-anything-v0.1": sm.get("retrieval_seconds"),
        "gpt6-astra-agent-v0.1": None,
    }[mid]
    gen = {
        "physx-anything-v0.1": rsum(sm, "decoder_seconds", "split_seconds", "export_seconds"),
        "physx-omni-v0.1": sm.get("geometry_total_runtime_seconds"),
        "pact-v0.1": sm.get("official_wall_seconds"),
        "partcrafter-v0.1": rsum(sm, "generation_seconds", "export_seconds"),
        "trellis2-4b-v0.1": rsum(sm, "generation_seconds", "export_seconds"),
        "articulate-anything-v0.1": rsum(sm, "link_seconds", "joint_seconds"),
        "gpt6-astra-agent-v0.1": sm.get("wall_seconds"),
    }[mid]
    e2e = t["e2e_native_median_s"] if nat else t["e2e_adapted_median_s"]
    e2m = t["e2e_native_mean_s"] if nat else t["e2e_adapted_mean_s"]
    wm = t["worker_minutes_per_native_pass"] if nat else t["worker_minutes_per_adapted_pass"]
    if mid in API_TIMED and not ct and e2e is not None:  # median rule for the API rows, as in Table 1
        kk = c["native_pass"] if nat else c["adapted_pass"]
        wm = round(e2e / 60 / (kk / sub["denominator"]), 1) if kk else None
    tag = api_tag(mid, "" if nat else DDG)
    return dict(
        perception=perc,
        generation=gen,
        adaptation=t.get("adapted_materialize_median_s"),
        validation=(t["native_gate_median_s"] if nat else None),
        e2e=e2e,
        e2e_tag=tag,
        throughput=(60 / wm if wm else None),
        wmin=wm,
        gpu_time=e2m,
        peak=(t.get("peak_gib_max") or None),
        api=(
            "0" if mid in ("physx-anything-v0.1", "physx-omni-v0.1", "pact-v0.1", "trellis2-4b-v0.1") else api_cell(mid)
        ),
    )


ours = dict(
    perception=XA["group_median"]["perception"],
    generation=XA["group_median"]["adaptation"],
    adaptation=None,
    validation=XA["group_median"]["validation"],
    e2e=T["e2e_median"],
    e2e_tag=DG,
    throughput=60 / XA["gpu_min_per_pass"],
    gpu_time=RES["worker_wall_seconds_per_case"],
    peak=peak,
    api="0",
)
if CLEAN_OURS:
    ours = dict(
        perception=CO["group"]["perception"]["median"],
        generation=CO["group"]["adaptation"]["median"],
        adaptation=None,
        validation=CO["group"]["validation"]["median"],
        e2e=CO["e2e_median"],
        e2e_tag="",
        throughput=60 / O1["wmin"],
        wmin=O1["wmin"],
        gpu_time=CO["e2e_mean"],
        peak=O1["peak"],
        api="0",
    )
cols = [ours] + [rcol(mid) for _, mid in RCOLS[1:]]


def fmt(v, f="{:.1f}", tag=""):
    return "" if v is None else (v if isinstance(v, str) else f.format(v) + tag)


rows = [
    ("Perception / retrieval (s)", "perception"),
    ("Generation (s)", "generation"),
    ("Adaptation to our contract (s)", "adaptation"),
    ("Physical validation (s)", "validation"),
    ("E2E median (s)", "e2e"),
    ("Throughput (passes / worker-h)", "throughput"),
    (("Minutes per accepted asset (median)", "wmin") if CLEAN_OURS else ("GPU time per input (mean s)", "gpu_time")),
    ("Peak GPU memory (GiB)", "peak"),
    ("API cost (USD / input)", "api"),
]
filled = [n.replace(BS, " ") for (n, mid), c in zip(RCOLS[1:], cols[1:]) if c]
L = [
    GEN
    + " Sources: "
    + (f"{CLEAN_SRC} (clean timing run) and " if CLEAN_OURS else "the campaign records (dagger) and ")
    + EXT_SRC
    + " (complete external runs only; "
    + (", ".join(x.replace("\\", " ") for x in filled) if filled else "none complete yet")
    + ").",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{2.5pt}",
    r"\renewcommand{\arraystretch}{1.05}",
]
L += [
    r"\caption{\textbf{Matched resource accounting on the full-RGB comparison.} "
    + (
        r"All times come from the clean timing run (one worker per exclusive RTX 5090; the PhysX-Omni geometry stage on an RTX PRO 6000) over a 32-input sample of the registered subset, \method\ with the geometry of its library entries built once; pass rates from the registered inputs of each Table~\ref{tab:main} row."
        if CLEAN_OURS
        else r"Each external column covers the registered inputs of its Table~\ref{tab:main} row."
    ),
    r"Per-input medians of the stage wall times each stage process recorded; adaptation is our common physical adaptation of the delivered asset (not applicable to \method, whose generation row is its own adaptation);",
    r"E2E, minutes per accepted asset, throughput and GPU time follow the native path where it applies and the adapted path ($\ddagger$) otherwise"
    + ("" if CLEAN_OURS else r"; $\dagger$: campaign throughput run on shared A100s")
    + r". API cost: official list prices of the model providers applied to the token counts each run recorded (gpt-6-astra: OpenAI Standard input, cached-input and cache-write rates; Gemini models: Google), 0 for methods that run only local models; $\S$: times of the API run itself.}",
]
L.append(r"\label{tab:resource-metrics}")
L.append(r"\begin{tabularx}{\linewidth}{@{}X" + " c" * len(RCOLS) + "@{}}")
L.append(r"\toprule")
L.append("Metric & " + " & ".join((mh(*n.split(BS)) if BS in n else n) for n, _ in RCOLS) + " " + BS + BS)
L.append(r"\midrule")
for label, key in rows:
    cells = []
    for c in cols:
        v = c.get(key) if c else None
        cells.append(
            fmt(v, "{:.1f}", c.get("e2e_tag", "") if key in ("e2e", "throughput", "gpu_time", "wmin") and c else "")
            if key != "api"
            else (v or "")
        )
    L.append(label + " & " + " & ".join(cells) + " " + BS + BS)
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("resource_metrics.tex", L)
resource_facts = dict(
    columns=[n for n, _ in RCOLS], ours=ours, external={mid: rcol(mid) for _, mid in RCOLS[1:]}, filled=filled
)


def _regime(o):
    return (
        None
        if not o
        else dict(
            n=o["n"],
            passes=o["passes"],
            e2e_median_s=o["e2e_median"],
            e2e_mean_s=o["e2e_mean"],
            e2e_p95_s=o["e2e_p95"],
            e2e_max_s=o.get("e2e_max"),
            worker_min_per_pass_2000=round(o["e2e_median"] / 60 / (k / n), 1),
            worker_min_per_pass_2000_mean=round(o["e2e_mean"] / 60 / (k / n), 1),
            group_median={g: v["median"] for g, v in o["group"].items()},
            peak_gib=max([(x.get("monitor") or {}).get("peak_gib") or 0 for x in o["shards"]] or [0]) or None,
        )
    )


resource_facts["clean_timing"] = (
    dict(
        source=CLEAN_SRC,
        regime_reported=OURS_REGIME if CLEAN_OURS else None,
        cold=_regime((CLEAN or {}).get("ours", {}).get("cold")),
        warm=_regime((CLEAN or {}).get("ours", {}).get("warm")),
        campaign_same_ids=(CLEAN or {}).get("ours", {}).get("campaign_same_ids"),
    )
    if CLEAN
    else None
)
json.dump(
    dict(
        main_table=facts,
        resource_table=resource_facts,
        development=dev,
        cluttered_development=mo,
        formal_exp1=dict(
            k=k,
            n=n,
            failure_reasons=x1["failure_reasons_nonexclusive"],
            attempts=x1["attempt_status_counts"],
            repairs_attempted=x1["repairs_attempted"],
            passes_with_repaired_asset=x1["passes_whose_selected_asset_was_repaired"],
            by_category={c: (v["physical_pass"], v["n"]) for c, v in x1["by_category"].items()},
        ),
        formal_exp2=dict(
            predictions=x2["denominator"],
            prediction_passes=x2["physical_pass"],
            localized=ref["localized"],
            passes=ref["physical_passes"],
            all_object_images=ref["all_object_images"],
            matching=ref["matching"],
            ci_localized=wilson(105, 237),
            ci_pass=wilson(100, 237),
            ci_images=wilson(13, 50),
            scope="main campaign alone: 32 images with valid first-pass detections; superseded by exp2_union",
        ),
        exp2_union=dict(
            source=str(IN / "campaign/exp2_union_summary.json"),
            detections=U["construction_pass_rate_over_predictions"]["union"]["records"],
            detection_passes=U["construction_pass_rate_over_predictions"]["union"]["physical_pass"],
            localized=U["union"]["localized"],
            passes=U["union"]["physical_passes"],
            all_object_images=U["union"]["all_object_images"],
            ci_localized=wilson(U["union"]["localized"], 237),
            ci_pass=wilson(U["union"]["physical_passes"], 237),
            ci_images=wilson(U["union"]["all_object_images"], 50),
            per_category=U["per_category_union"],
            record_sources={
                kk: {a: b for a, b in v.items() if a in ("images", "records", "physical_pass")}
                for kk, v in U["record_sources"].items()
            },
        ),
        subset200=dict(
            k=ks,
            n=ns,
            receipt=str(IN / "campaign/subset200_from_formal013.json"),
            per_case_sha256=S200["per_case_sha256"],
            subset_sha256=S200["subset_sha256"],
        ),
    ),
    open(
        (OUT / "facts").mkdir(parents=True, exist_ok=True) or OUT / "facts" / "comparison_facts.json",
        "w",
        encoding="utf-8",
    ),
    indent=1,
)
print(
    "tables written; exp1",
    k,
    "/",
    n,
    "subset",
    ks,
    "/",
    ns,
    "exp2",
    ref["localized"],
    ref["physical_passes"],
    ref["all_object_images"],
)
