"""Appendix tables, all read from recorded files (paths relative to --inputs); edit this generator, not the numeric cells.
  tables/asset_gallery.tex     the 30 assets of the appendix gallery figure (label, category, input, library entry, support
                               role, uniform scale, driven joint and its travel) from gallery/s02_asset_gallery.json
  tables/vla_collection.tex    per scene: the frozen instruction and the outcome of the three collection rounds
                               (collect20 teacher, dagger20, dagger20r2) from scenes/fig7_export/collection_stats.json +
                               manifest.json; the instruction sits on its own full-width line under the scene (two rows per scene)
  tables/vla_failure_modes.tex per scene: outcome classes of the 100 held-out round-2 episodes from
                               scenes/fig7_export/failure_modes_round2.json (the classes the appendix text totals)
  tables/vla_hparams.tex       the action-head training configuration from scenes/round2/configuration.json
  tables/subset200.tex         per category: inputs and passes of the 2,000-input campaign and of the registered 200-input subset
                               (campaign/subset200_from_formal013.json, evidence_v2 by_category)
  tables/campaign_timing.tex   recorded wall-clock of the 2,000-input campaign per phase, per phase group and end to end
                               (evidence_v2 main_campaign.exp1.timing_seconds)
Files are written with CRLF line endings like the other generated tables."""

import json, math
from pathlib import Path
import argparse

_AP = argparse.ArgumentParser(description="appendix tables")
_AP.add_argument(
    "--inputs",
    default=str(Path(__file__).resolve().parents[1] / "results"),
    help="recorded inputs (layout of analysis/results)",
)
_AP.add_argument(
    "--out",
    default=str(Path(__file__).resolve().parents[1] / "out"),
    help="output directory (tables/, figures/, facts/, sections/)",
)
_A = _AP.parse_args()
IN = Path(_A.inputs)
OUT = Path(_A.out)
TAB = OUT / "tables"
TAB.mkdir(parents=True, exist_ok=True)
F7 = IN / "scenes/fig7_export"


def load(p):
    return json.load(open(p, encoding="utf-8"))


def write(name, lines):
    (TAB / name).write_text("\r\n".join(lines) + "\r\n", encoding="utf-8", newline="")


GEN = "% Generated by analysis/tables/tables_appendix.py"
# ---------------------------------------------------------------- asset gallery table
G = load(IN / "gallery/s02_asset_gallery.json")["facts"]["assets"]


def input_cell(iid):
    if iid.startswith("openimages_"):
        return "OI " + iid[len("openimages_") :][:8]
    if "_coco_" in iid:  # scene_030_coco_000000001993__det_007 -> cluttered image, COCO id, detection index
        sc, rest = iid.split("_coco_")
        img, det = rest.split("__det_")
        return f"COCO {int(img)}, det.\\ {int(det)}"
    return iid


def entry_cell(cid):
    return cid[len("objaverse_") :][:8] if cid.startswith("objaverse_") else cid


def joint_cell(j):
    if j is None:
        return "rigid & --"
    if j["type"] == "revolute":
        return f"revolute & {j['travel_deg']:.0f}$^\\circ$"
    t = j["travel_m"]
    return "prismatic & " + (f"{100*t:.0f} cm" if abs(t) >= 0.01 else f"{1000*t:.1f} mm")


L = [
    GEN
    + " from gallery/s02_asset_gallery.json (facts of the gallery figure receipt: the assets of the appendix gallery figure). Edit the generator, not the cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{3pt}",
    r"\renewcommand{\arraystretch}{1.05}",
    r"\caption{\textbf{Assets of the gallery figure.}",
    "Rows follow the figure. Input: Open Images id prefix (OI) or the COCO",
    "image and detection index of a cluttered-image input. Entry: the",
    "PartNet-Mobility id or the Objaverse id prefix of the selected library",
    "entry. Role: free-standing or mounted support. Scale: the uniform scale",
    "the adapter applied. Joint and travel: type of the driven joint and its",
    "displacement between the two rendered states, read back from the",
    "simulator and signed along the joint axis; the bottle is a rigid entry",
    "with no joint.}",
    r"\label{tab:gallery}",
    r"\begin{tabularx}{\linewidth}{@{}Z l l l l r l r@{}}",
    r"\toprule",
    r"Asset & Category & Input & Entry & Role & Scale & Joint & Travel \\",
    r"\midrule",
]
for a in G:
    j = a["joint"]
    cat = (
        a["category"]
        .replace("StorageFurniture", "Storage")
        .replace("WashingMachine", "Washer")
        .replace("CoffeeMachine", "Coffee machine")
        .replace("TrashCan", "Trash can")
    )
    sc = a["uniform_scale"]
    scale = (
        f"{sc:.2f}" if sc >= 0.01 else f"{sc:.5f}"
    )  # the bottle (3.5e-4) as plain decimals: a wide Scale cell made four Asset cells wrap
    L.append(
        f"{a['label']} & {cat} & {input_cell(a['input_id'])} & {entry_cell(a['cid'])} & {a['role']} & {scale} & {joint_cell(j)} \\\\"
    )
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("asset_gallery.tex", L)
# ---------------------------------------------------------------- collection rounds + instructions
M = load(F7 / "manifest.json")
cs = load(F7 / "collection_stats.json")
DS = load(IN / "scenes/round2/dataset/manifest.json")
assert DS["episode_count"] == 664 and sum(DS["per_scene"].values()) == 664
ORDER = [
    "cabinet_cup",
    "cabinet1_box",
    "fridge_cup",
    "microwave_box",
    "drawer_cup",
    "drawer_two",
    "drawer_to_cabinet",
    "drawer_to_fridge",
    "laptop_cup",
    "trashcan_box",
]
SHORT = {
    "cabinet_cup": "Cabinet (2-door) + cup",
    "cabinet1_box": "Cabinet (1-door) + box",
    "fridge_cup": "Refrigerator + cup",
    "microwave_box": "Microwave + box",
    "drawer_cup": "Drawer + cup",
    "drawer_two": "Drawer + two cups",
    "drawer_to_cabinet": r"Drawer$\to$cabinet + cup",
    "drawer_to_fridge": r"Drawer$\to$fridge + cup",
    "laptop_cup": "Laptop + cup",
    "trashcan_box": "Trash can + box",
}
tot = {
    r: dict(
        episodes=sum(cs[r][s]["episodes"] for s in ORDER),
        passed=sum(cs[r][s]["passed"] for s in ORDER),
        stage1=sum(cs[r][s]["stage1"] for s in ORDER),
    )
    for r in ("collect20", "dagger20", "dagger20r2")
}
assert (
    tot["collect20"] == dict(episodes=320, passed=273, stage1=298)
    and tot["dagger20"]["episodes"] == 200
    and tot["dagger20r2"]["episodes"] == 240
)
L = [
    GEN
    + " from scenes/fig7_export/collection_stats.json and manifest.json (instructions). Edit the generator, not the cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{3pt}",
    r"\renewcommand{\arraystretch}{1.05}",
    r"\caption{\textbf{Instructions and data-collection rounds per scene.}",
    "Under each scene stands the instruction string every teacher and policy",
    "episode of that scene received. Each round lists task successes",
    "$\\cdot$ first-sub-goal completions over its episodes: the teacher",
    "round (32 per scene) and the two rounds of mixed rollouts driven by the",
    "first and second trained heads (20 and 24 per scene). Ticks: median",
    "length of the passed teacher episodes at 10 Hz. Train: episodes of the",
    "scene in the final training set after the exclusions described under",
    "Data and training (Table~\\ref{tab:vla-rounds}, last row).}",
    r"\label{tab:vla-collection}",
    r"\begin{tabularx}{\linewidth}{@{}X c c c r r@{}}",
    r"\toprule",
    r"Scene and instruction & \metrichead{Teacher\\task $\cdot$ sg1 /32} & \metrichead{Rollouts 1\\task $\cdot$ sg1 /20} & \metrichead{Rollouts 2\\task $\cdot$ sg1 /24} & Ticks & Train \\",
    r"\midrule",
]
for (
    s
) in (
    ORDER
):  # two rows per scene: the counts beside the scene name, the verbatim instruction on a full-width line below it
    a, b, c = cs["collect20"][s], cs["dagger20"][s], cs["dagger20r2"][s]
    assert (a["episodes"], b["episodes"], c["episodes"]) == (32, 20, 24)
    L.append(
        f"{SHORT[s]} & {a['passed']}$\\cdot${a['stage1']} & {b['passed']}$\\cdot${b['stage1']} & {c['passed']}$\\cdot${c['stage1']} & {a['passed_ticks_median']:.0f} & {DS['per_scene'][s]} \\\\"
    )
    L.append(f"\\multicolumn{{6}}{{@{{}}l@{{}}}}{{\\quad\\emph{{{M['scenes'][s]['instruction']}}}}} \\\\")
L.append(r"\midrule")
L.append(
    f"Total & {tot['collect20']['passed']}$\\cdot${tot['collect20']['stage1']} /320 & {tot['dagger20']['passed']}$\\cdot${tot['dagger20']['stage1']} /200 & {tot['dagger20r2']['passed']}$\\cdot${tot['dagger20r2']['stage1']} /240 & & {DS['episode_count']} \\\\"
)
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("vla_collection.tex", L)
# ---------------------------------------------------------------- failure modes of the 100 held-out episodes
FMD = load(F7 / "failure_modes_round2.json")
rows = FMD["rows"]
assert FMD["n"] == 100 and len(rows) == 100
COLS = [
    ("passed", "Pass"),
    ("after_stage1_grasp_missed", "Grasp missed"),
    ("after_stage1_lifted_not_placed", "Lifted, not placed"),
    ("after_stage1_not_grasped", "Not grasped"),
    ("stage1_articulation_untouched", "Untouched"),
    ("stage1_articulation_partial", "Partial"),
    ("stage1_transfer_grasp", "Grasp missed"),
    ("stage1_transfer_lifted", "Lifted, not placed"),
]


def cls(m):
    if m in ("after_stage1_not_approached", "after_stage1_approached_no_grasp"):
        return "after_stage1_not_grasped"
    if m in ("stage1_transfer_not_placed_grasp_missed", "stage1_transfer_not_placed_not_approached"):
        return "stage1_transfer_grasp"
    if m == "stage1_transfer_not_placed_lifted":
        return "stage1_transfer_lifted"
    return m


cnt = {s: {k: 0 for k, _ in COLS} for s in ORDER}
for r in rows:
    cnt[r["scene"]][cls(r["mode"])] += 1
tot = {k: sum(cnt[s][k] for s in ORDER) for k, _ in COLS}
assert tot == {
    "passed": 11,
    "after_stage1_grasp_missed": 30,
    "after_stage1_lifted_not_placed": 12,
    "after_stage1_not_grasped": 13,
    "stage1_articulation_untouched": 10,
    "stage1_articulation_partial": 7,
    "stage1_transfer_grasp": 13,
    "stage1_transfer_lifted": 4,
}, tot
assert sum(tot.values()) == 100


def cell(v):
    return str(v) if v else "--"


L = [
    GEN
    + " from scenes/fig7_export/failure_modes_round2.json (round-2 held-out evaluation, trained head, 10 episodes per scene). Edit the generator, not the cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{3pt}",
    r"\renewcommand{\arraystretch}{1.05}",
    r"\caption{\textbf{Outcome of the 100 held-out episodes of the trained head.}",
    "Ten episodes per scene, classified from the recorded trace. After the",
    "first sub-goal: the gripper closed beside the object without securing it",
    "(grasp missed), lifted it and released it outside the target volume",
    "(lifted, not placed), or never closed on it (not grasped; one of the 13",
    "approached without closing). Before the first sub-goal: the door, drawer,",
    "or lid stayed untouched or moved partly (mechanism columns), or, in the",
    "two transfer scenes, the cup was not carried out of the drawer (grasp",
    "missed, or lifted and dropped back).}",
    r"\label{tab:vla-failures}",
    r"\begin{tabularx}{\linewidth}{@{}X r r r r r r r r@{}}",
    r"\toprule",
    r" & & \multicolumn{3}{c}{After first sub-goal} & \multicolumn{2}{c}{Mechanism short} & \multicolumn{2}{c}{Transfer, cup not out} \\",
    r"\cmidrule(lr){3-5}\cmidrule(lr){6-7}\cmidrule(l){8-9}",
    r"Scene & Pass & Grasp & Lifted & Not grasped & Untouched & Partial & Grasp & Lifted \\",
    r"\midrule",
]
for s in ORDER:
    L.append(f"{SHORT[s]} & " + " & ".join(cell(cnt[s][k]) for k, _ in COLS) + r" \\")
L.append(r"\midrule")
L.append("Total & " + " & ".join(str(tot[k]) for k, _ in COLS) + r" \\")
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("vla_failure_modes.tex", L)
# ---------------------------------------------------------------- action-head hyperparameters
C = load(IN / "scenes/round2/configuration.json")
ac = C["action_contract"]


def sci(v):
    e = math.floor(math.log10(v) + 1e-12)
    m = v / 10**e
    assert abs(m - round(m, 3)) < 1e-9, (v, m)
    return (f"{round(m,3):g}\\times" if abs(m - 1) > 1e-9 else "") + f"10^{{{e}}}"


assert sci(0.0003) == "3\\times10^{-4}" and sci(0.0001) == "10^{-4}", (sci(0.0003), sci(0.0001))
assert (
    ac["action_chunk_length"] == 8
    and ac["executed_prefix"] == 4
    and ac["control_hz"] == 10
    and ac["physics_hz"] == 60
    and C["memory_width"] == 512
    and C["feature_dim"] == 8192
)
H = [
    ("Backbone", "OpenVLA-OFT, LIBERO-Spatial checkpoint, frozen"),
    ("Per-image feature", "mean of the 56 action-token states, 4,096-d"),
    ("Images per step", f"{C['num_images']} (third-person crop, wrist), 320$\\times$240"),
    ("Feature input to head", f"\\num{{{C['feature_dim']}}}-d (two images concatenated)"),
    ("Proprioception", f"{ac['proprio_dim']} joint positions (7 arm, 2 finger)"),
    ("Head", "GRU, " + str(C["memory_width"]) + " units"),
    (
        "Action chunk",
        f"{ac['action_chunk_length']} future targets, {ac['executed_prefix']} executed, {ac['action_dim']}-d",
    ),
    ("Arm targets", "delta to the chunk-start joint state, per-horizon scaled"),
    ("Control / physics rate", f"{ac['control_hz']} Hz / {ac['physics_hz']} Hz"),
    ("Optimizer", f"AdamW, learning rate ${sci(C['learning_rate'])}$, weight decay ${sci(C['weight_decay'])}$"),
    ("Schedule", f"{C['warmup_steps']} warm-up steps, cosine decay, \\num{{{C['max_steps']}}} steps"),
    ("Batch size", str(C["batch_size"])),
    ("Motion loss weight", f"{C['motion_loss_gain']} (scale {C['motion_loss_scale_rad']} rad)"),
    ("Temporal consistency weight", str(C["temporal_consistency_lambda"])),
    ("Query overlap weight", str(C["query_overlap_lambda"])),
    (
        "Proprioception noise",
        f"std {C['proprio_noise_std_rad']} rad, correlation {C['proprio_noise_correlation']}, p = {C['proprio_augmentation_probability']}",
    ),
    (
        "Seeds",
        f"{C['seed']} (training), {C['adapter_initialization_seed']} (head init), {C['augmentation_seed']} (augmentation)",
    ),
    (
        "Prompt",
        r"\texttt{In: What action should the robot take to \{instruction\}?\textbackslash{}nOut:} (instruction in lower case)",
    ),
]
assert C["prompt_template"] == "In: What action should the robot take to {frozen_instruction_stripped_lowercase}?\nOut:"
L = [
    GEN
    + " from scenes/round2/configuration.json (the registered round-2 training run). Edit the generator, not the cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\small",
    r"\setlength{\tabcolsep}{4pt}",
    r"\renewcommand{\arraystretch}{1.08}",
    r"\caption{\textbf{Action-head configuration of the scene study.}",
    "Values of the registered round-2 training run. The backbone is never",
    "finetuned; the untrained condition uses the same head at initialization.}",
    r"\label{tab:vla-hparams}",
    r"\begin{tabularx}{\linewidth}{@{}l Z@{}}",
    r"\toprule",
    r"Setting & Value \\",
    r"\midrule",
]
for k, v in H:
    L.append(f"{k} & {v} \\\\")
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("vla_hparams.tex", L)
# ---------------------------------------------------------------- 200-input subset composition
S = load(IN / "campaign/subset200_from_formal013.json")
E = load(IN / "campaign/evidence_v2_20260920-181120.json")["main_campaign"]["exp1"]["by_category"]
assert (
    S["subset_n"] == 200
    and S["subset_physical_pass"] == 167
    and sum(S["subset_inputs_by_category"].values()) == 200
    and sum(S["subset_pass_by_category"].values()) == 167
)
cats = sorted(E, key=lambda k: (-E[k]["n"], k))
NAME = {
    "StorageFurniture": "Storage",
    "Refrigerator": "Fridge",
    "WashingMachine": "Washer",
    "CoffeeMachine": "Coffee maker",
    "TrashCan": "Trash can",
}
half = (len(cats) + 1) // 2
left, right = cats[:half], cats[half:]


def row(k):
    if k is None:
        return " & & & & "
    return f"{NAME.get(k,k)} & {E[k]['n']} & {E[k]['physical_pass']} & {S['subset_inputs_by_category'].get(k,0)} & {S['subset_pass_by_category'].get(k,0)}"


L = [
    GEN
    + " from campaign/subset200_from_formal013.json and campaign/evidence_v2_20260920-181120.json. Edit the generator, not the cells.",
    r"\begin{table}[t]",
    r"\centering",
    r"\footnotesize",
    r"\setlength{\tabcolsep}{3pt}",
    r"\renewcommand{\arraystretch}{1.05}",
    r"\caption{\textbf{Composition of the 200-input subset.}",
    "Per category: inputs and physical passes of the full 2,000-input campaign",
    "and of the registered 200-input subset shared with the external methods",
    "(seed 20260916, at least one input per category, the rest in proportion",
    "to category size). The subset passes are a recount of the campaign",
    "records on those inputs, not a new run.}",
    r"\label{tab:subset}",
    r"\begin{tabularx}{\linewidth}{@{}X r r r r @{\hspace{10pt}} X r r r r@{}}",
    r"\toprule",
    r"Category & \multicolumn{2}{c}{All 2,000} & \multicolumn{2}{c}{Subset} & Category & \multicolumn{2}{c}{All 2,000} & \multicolumn{2}{c}{Subset} \\",
    r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){7-8}\cmidrule(l){9-10}",
    r" & In. & Pass & In. & Pass & & In. & Pass & In. & Pass \\",
    r"\midrule",
]
for i in range(half):
    L.append(row(left[i]) + " & " + row(right[i] if i < len(right) else None) + r" \\")
L.append(r"\midrule")
L.append(f"Total & 2,000 & 1,703 & 200 & 167 & & & & & \\\\")
L += [r"\bottomrule", r"\end{tabularx}", r"\end{table}"]
write("subset200.tex", L)
print("appendix tables written:", len(G), "assets;", tot)
# ---------------------------------------------------------------- recorded campaign timing (exp1, verified final results)
B = chr(92)
RE = B * 2
EV = load(IN / "campaign/evidence_v2_20260920-181120.json")["main_campaign"]
X1 = EV["exp1"]
T = X1["timing_seconds"]
RS = EV["resources"]
CN = EV["construction"]
RC = load(IN / "campaign/timing_from_formal013.json")
S2 = load(IN / "campaign/subset200_from_formal013.json")
P9 = load(IN / "campaign/timing_p90_from_formal013.json")
assert (
    P9["per_case_sha256"] == RC["per_case_sha256"]
    and P9["e2e"]["n"] == 2000
    and abs(P9["e2e"]["p95_linear_interpolation"] - RC["e2e"]["p95_linear_interpolation"]) < 1e-6
)
assert RC["per_case_sha256"] == S2["per_case_sha256"] and RC["inputs"] == 2000 and RC["e2e"]["n"] == 2000
assert (
    X1["denominator"] == 2000
    and X1["completed_cases"] == 2000
    and X1["verified_final_results"] is True
    and X1["physical_pass"] == 1703
)
assert "concurrent workers per GPU" in T["note"] and "pre-warmed geometry cache" in T["note"], T["note"]
for k, v in RC["phases"].items():
    assert abs(v["median"] - T["per_phase_median"][k]) < 1e-6 and abs(v["mean"] - T["per_phase_mean"][k]) < 1e-6, k
for k, v in RC["groups"].items():
    assert (
        abs(v["median"] - T["per_case_group_median"][k]) < 1e-6 and abs(v["mean"] - T["per_case_group_mean"][k]) < 1e-6
    ), k
assert (
    abs(RC["e2e"]["median"] - T["e2e_median"]) < 1e-6
    and abs(RC["e2e"]["mean"] - T["e2e_mean"]) < 1e-6
    and abs(RC["e2e"]["p95_linear_interpolation"] - T["e2e_p95"]) < 1e-6
)
assert (
    abs(T["e2e_median"] - 85.0) < 0.01 and abs(T["e2e_mean"] - 602.39) < 0.01 and abs(T["e2e_p95"] - 2873.46) < 0.01
), (T["e2e_median"], T["e2e_mean"], T["e2e_p95"])
assert (
    round(T["per_case_group_median"]["perception"], 1),
    round(T["per_case_group_median"]["adaptation"], 1),
    round(T["per_case_group_median"]["validation"], 1),
) == (31.6, 67.3, 6.5)
assert (CN["candidates"], CN["batch_size"], CN["materialization_timeout_seconds"]) == (20, 5, 600) and round(
    T["considered_candidates_mean"], 1
) == 2.9
assert sum(X1["attempt_status_counts"].values()) == 5874 == RC["attempts"] and round(5874 / 2000, 3) == round(
    T["considered_candidates_mean"], 3
)
assert (
    RC["attempts_with_a_repair"] == X1["repairs_attempted"] == 179
    and RC["repair_calls"] == RC["phases"]["repair"]["n"] == 3138
)
assert (RC["groups"]["perception"]["n"], RC["groups"]["adaptation"]["n"], RC["groups"]["validation"]["n"]) == (
    2000,
    1767,
    1712,
)
assert (
    round(RS["peak_gpu_memory_mib_per_worker_tree_median"] / 1024, 1),
    round(RS["peak_gpu_memory_mib_per_worker_tree_max"] / 1024, 1),
) == (29.0, 32.3)
assert round(RS["model_load_seconds_median"], 1) == 16.2 and round(RS["offline_index_wall_seconds"]) == 1190
PH = [
    ("grounding", "Grounding", "perception"),
    ("retrieval", "Retrieval", "perception"),
    ("multimodal_ranking", "Multimodal ranking", "perception"),
    ("asset_construction", "Asset construction", "adaptation"),
    ("repair", "Repair", "adaptation"),
    ("construction_physics", "Construction physics", "validation"),
    ("final_physics", "Final physics", "validation"),
]
assert set(k for k, _, _ in PH) == set(T["per_phase_median"]) == set(T["per_phase_mean"]) == set(RC["phases"])
GR = [("perception", "Perception"), ("adaptation", "Adaptation"), ("validation", "Validation")]
assert set(k for k, _ in GR) == set(T["per_case_group_median"]) == set(RC["groups"])


def sec(v):
    return f"{v:,.2f}"


def num(n):
    return f"{n:,}"


L = [
    GEN
    + " from campaign/evidence_v2_20260920-181120.json (main_campaign.exp1.timing_seconds) and campaign/timing_from_formal013.json (execution counts; same verified per-case file). Edit the generator, not the cells.",
    B + "begin{table}[t]",
    B + "centering",
    B + "footnotesize",
    B + "setlength{" + B + "tabcolsep}{3pt}",
    B + "renewcommand{" + B + "arraystretch}{1.05}",
    B + "caption{" + B + "textbf{Recorded timing of the formal campaign.}",
    "Wall-clock seconds over the 2,000 single-object inputs, from the verified",
    "per-input records of a throughput run (concurrent workers per GPU,",
    "pre-computed geometry cache), so not exclusive-device latencies. Phase",
    "rows: median and mean over the $n$ recorded executions of the phase;",
    "repair runs at most once per attempt, after a failed export or a failed",
    f"construction check, and returned a repaired asset in {RC['attempts_with_a_repair']} attempts. Group",
    "rows: per input, over the $n$ inputs that reached the group. End to end:",
    "per input; the P90 is",
    f"{P9['e2e']['p90_linear_interpolation']:,.0f} s.}}",
    B + "label{tab:campaign-timing}",
    B + "begin{tabularx}{" + B + "linewidth}{@{}X l r r r@{}}",
    B + "toprule",
    "Stage & Group & $n$ & Median (s) & Mean (s) " + RE,
    B + "midrule",
]
for k, lab, g in PH:
    L.append(
        f"{lab} & {g} & {num(RC['phases'][k]['n'])} & {sec(T['per_phase_median'][k])} & {sec(T['per_phase_mean'][k])} "
        + RE
    )
L.append(B + "midrule")
for k, lab in GR:
    L.append(
        f"{lab}, per input & & {num(RC['groups'][k]['n'])} & {sec(T['per_case_group_median'][k])} & {sec(T['per_case_group_mean'][k])} "
        + RE
    )
L.append(f"End to end, per input & & {num(RC['e2e']['n'])} & {sec(T['e2e_median'])} & {sec(T['e2e_mean'])} " + RE)
L += [B + "bottomrule", B + "end{tabularx}", B + "end{table}"]
write("campaign_timing.tex", L)
print(
    "campaign timing written; e2e p95",
    round(T["e2e_p95"], 1),
    "repair calls",
    RC["repair_calls"],
    "repaired",
    RC["attempts_with_a_repair"],
)
